### ISSUE TITLE
Rename the library

### ISSUE THREAD

**Issue by avin-kavish** [microsoft/tsyringe#100]
**TSyringe** is hard to pronounce. I suggest we call it just **Syringe**.

**Comment by MeltingMosaic** [comment]
Think of the pronunciation as "Syringe" but with the "S" sound from "it's". Also, I don't think changing the name is necessary, and doing so would make it harder to Google.

**Comment by Xapphire13** [comment]
Also, the name is a combination of TS from TypeScript, and Syringe from injection; so it would lose its semantic value if we renamed.
