### ISSUE TITLE
Injecting the container instance

### ISSUE THREAD

**Issue by Lusito** [microsoft/tsyringe#102]
**Is your feature request related to a problem? Please describe.**
There are situations, where I need to create instances of a class based on events. In these cases, I'd like to be able to ask the container for a new instance, but currently it doesn't seem possible to inject the container as a dependency.

**Description**
I'd like something along the lines of:
```typescript
@injectable()
class Foo {
  constructor(private container: DependencyContainer ) {}
  onContextCreated() {
     const contextListener = this.container.resolve(ContextListener);
     //...
  }
}
```

**Alternate solutions**
- I guess it might be possible to use registerInstance for this, but that doesn't seem very clean.
- Using global context is not always a viable option

I'm still new to dependency injection, so maybe I'm missing a different pattern that should be used in such cases, but at least one other di lib supports this: https://github.com/justmoon/constitute#containers

**Comment by MeltingMosaic** [comment]
I haven't tried this, but I think you can register the `DependencyContainer` manually, but I don't think we do that by default since it can result in usage of some anti-patterns (namely, Service Locator). You may have a valid exception to that if you can't find a way to inject `ContextListener` or a factory for it via the constructor.

**Comment by Lusito** [comment]
No matter what I try to register `DependencyContainer`, I always get:
```
Error: Cannot inject the dependency at position #0 of "Foo" constructor. Reason:
    TypeInfo not known for "Object"
```

```typescript
// This doesn't work either:
// container.register("DependencyContainer", { useFactory: (c) => c });

@injectable()
@registry([
  {
    token: "DependencyContainer",
    useFactory: (c) => c
  }
])
class Foo {
    constructor(public container: DependencyContainer) {
        // This sample is simplified.. I wouldn't use it in the constructor
        const bar = container.resolve(Bar);
    }
}
```

I'm guessing the above doesn't work, because it can't associate the interface with the string token somehow. Though I thought this was supposed to work.

This way seems to work, but is a bit ugly:

```typescript

class MyContainer {
    constructor(public container: DependencyContainer) {
    }
}
container.register(MyContainer , { useFactory: (c) => new MyContainer (c) });

@injectable()
class Foo {
    constructor(public container: MyContainer) {
        // This sample is simplified.. I wouldn't use it in the constructor
        const bar = container.container.resolve(Bar);
    }
}

```

Taking this a step further, I guess this is somewhat acceptable:

```typescript
class BarFactory {
    constructor(private container: DependencyContainer) {}
    create(): Bar {
        return this.container.resolve(Bar);
    }
}
container.register(BarFactory, { useFactory: (c) => new BarFactory(c) });

@injectable()
class Foo {
    constructor(public barFactory: BarFactory) {
        // This sample is simplified.. I wouldn't use it in the constructor
        const bar= barFactory.create();
    }
}
```

Not sure if there is an anti-pattern in there though

**Comment by MeltingMosaic** [comment]
I think your last example (with `BarFactory`) is probably the way to go for delayed resolution. That way, `Foo` never needs to know anything about the container, and `BarFactory` only uses it as much as necessary.

**Comment by Lusito** [comment]
I'm gonna go with that for now. Thanks for the feedback
