### ISSUE TITLE
Custom parameter decorator

### ISSUE THREAD

**Issue by konuch** [microsoft/tsyringe#107]
Hello, first of all thanks for this great lib.
I would like to ask if there is a way to create a custom decorator, something like what can be done in https://github.com/typestack/typedi#custom-decorators.

I would like to create a custom decorator, for injecting TypeORM repository based on provided entity. Something like: `@InjectRepository(User) public repository: Repository<User>`, where @InjectRepository is my custom decorator.

Thanks in advance.

**Comment by Xapphire13** [comment]
Yep! You can do something similar to what is found [here](https://github.com/microsoft/tsyringe/blob/8671d1d11298945f4d2f8b35edb868bb4fdec398/src/decorators/singleton.ts#L13). Where you wrap the target of your custom decorator with any other decorators you wish to include
