### ISSUE TITLE
who register singleton

### ISSUE THREAD

**Issue by sptGabriel** [microsoft/tsyringe#119]
Hello i am in doubt how can i register a singleton and if i did it the right way

**repository**:

```
singleton()
export default class EmployeeRepository implements IRepository<Employee> {
  private ormRepository: Repository<Employee>;
  constructor() {
    this.ormRepository = getRepository(Employee);
  }
  readAll(): Promise<Employee[]> {
    throw new Error("Method not implemented.");
  }
  readOneById(id: string): Promise<Employee | undefined> {
    throw new Error("Method not implemented.");
  }
  create(data: Employee): Promise<Employee | undefined> {
    throw new Error("Method not implemented.");
  }

}
```

and service:

```
@injectable()
export class EmployeeServices {
  constructor(@inject('EmployeeRepository')
  private repository: EmployeeRepository) {
  }

  public create() {
    return `a`
  }
}
```

controller:
```

@singleton()
export class EmployeesController {
  readonly routes = Router();
  private services: EmployeeServices;
  constructor() {
    this.services = container.resolve(EmployeeServices)
  }
  public static() {

  }

}
```
here i register repository  keys on container:

 ```
 private registerRepositories() {
    let rootDir: string =
      process.env.NODE_ENV === 'development' ? 'src' : 'build/src';
    let pattern: string = rootDir + '/modules/**/repositories/*.{js,ts}';
    glob.sync(pattern).forEach(file => {
      let repository = require(resolve(file)).default;
      let name = repository.name;
      container.register(`${name}`, { useValue: repository });
      console.log(container.isRegistered(name))
    });
  }

```

I have some questions,
how do I register my singletons (controllers),

as my repository is a singleton, I could just use container.resolver (repository key)
in my service?

I'm a little confused by this

**Comment by Xapphire13** [comment]
The `@singleton` decorator registers the class as a singleton against the class itself as the injection token.

In your example, it looks like you want to have string tokens with the repository name; I would suggest not using `@singleton()` in this case, and changing your `registerRepositories()` code to use `container.registerSingleton(...)`.

Perhaps a feature could be added to allow `@singleton()` to take in an injection token. Would you find that helpful?

**Comment by sptGabriel** [comment]
thank u @Xapphire13
