### ISSUE TITLE
Singleton injected multiple times if token is different parent class

### ISSUE THREAD

**Issue by srolel** [microsoft/tsyringe#122]
**Describe the bug**

If I inject a class `Foo` with parent `Bar` as both `Foo` and `Bar`, it gets constructed twice.

**To Reproduce**

```
import 'reflect-metadata';
import { singleton, container } from 'tsyringe';

class Bar {}

@singleton()
class Foo extends Bar {
  constructor() {
    super();
    console.log('Foo');
  }
}

container.register(Bar, Foo); // same result if registerSingleton is used
container.register(Foo, Foo);

// "Foo" gets logged twice
container.resolve(Foo);
container.resolve(Bar);

```

**Expected behavior**

`Foo` should only be instantiated once.

**Version**:
4.3.0

**Comment by Xapphire13** [comment]
`@singleton` is simply a convenience method which registers a class, using that class as the token, as a singleton; that is, the singleton behavior is only when resolved via that token (you are free to register the same class with a different token, with non singleton behavior).

**Comment by frencojobs** [comment]
May I inquire how one could achieve the said behavior? In other words, how do I register a singleton class to two different tokens and have only one instantiated instance returned on all resolutions?

**Comment by WilliamXieMSFT** [comment]
Type/Interface forwarding can be done using `container.registerType("Bar", "Foo")` which effectively forwards the "Bar" token to the "Foo" token which maps to the singleton instance.
