### ISSUE TITLE
Basic constructor injection is not working as expected in react native

### ISSUE THREAD

**Issue by Thomas-X** [microsoft/tsyringe#124]
**Describe the bug**
When a class has a dependency in its constructor, tsyringe outputs the `Typeinfo not known for Sheep` 

**Steps to Reproduce**
run react native ignite with bowser template:
```
npx ignite-cli new tsyringereactnativetest
```

enable decorator settings in `tsconfig.json`, run `yarn add tsyringe reflect-metadata` and then go to `app.tsx` and paste this at the top: 
```typescript
import 'reflect-metadata'
import {container, inject, injectable} from 'tsyringe'

class Animal {
  constructor() {
  }
  makeSound (sound: string) {
    console.log(sound)
  }
}
@injectable()
class Sheep {
  _animal;
  constructor(animal: Animal) {
    this._animal = animal
  }

  beeeeh () {
    console.log("bleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh")
  }
}

console.log(container.resolve(Sheep).beeeeh())
```
I've tried mix and matching `@injectable` decorators, using `container.register(T, {token: T, useClass: T})`. Everything works A-Okay until I add a simple dependency in a constructor of my injected service. 

**Expected behavior**

That basic constructor injection works in a library about .. constructor injection. I hope I just made a dumb mistake 😄 
**Version**:
```json
    "reflect-metadata": "^0.1.13",
    "tsyringe": "^4.3.0",
```

**Comment by emilioastarita** [comment]
1. You are missing `emitDecoratorMetadata` in your `compilerOptions` :

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }

}
```

2. Then add `@injectable` decorator to class `Animal`.

```typescript
@injectable()
class Animal {
```


## Complete example:

```typescript
import 'reflect-metadata'
import {container, inject, injectable} from 'tsyringe'


@injectable()
export class Animal {
  makeSound (sound: string) {
    console.log(sound)
  }
}


@injectable()
class Sheep {

  constructor(private animal:Animal) {}

  beeeeh () {
    console.log("bleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh")
  }
}


container.resolve(Sheep).beeeeh();

```

Run with:

```bash
# build 
tsc --target ES5 --experimentalDecorators --emitDecoratorMetadata --lib es2015,dom example.ts
# run
node example.js
```

**Comment by Thomas-X** [comment]
> You are missing emitDecoratorMetadata in your compilerOptions :

Sadly that's not the case. See my full `tsconfig.json`:
```json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "jsx": "react-native",
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "sourceMap": true,
    "target": "esnext",
    "lib": ["esnext"],
    "skipLibCheck": true
  },
  "exclude": ["node_modules"],
  "include": ["index.js", "app", "test", "storybook"]
}
```
> Then add @injectable decorator to class Animal

I just did that, and that didn't help the problem 😭 .
I've posted my full example (it's just the ignite cli template and the paste, like described in the OP) [here](https://github.com/Thomas-X/playgroundReactnative/blob/master/app/app.tsx#L12)

**Comment by Thomas-X** [comment]
#111 is related to this I think, because in a pure typescript environment the DI works well. Otherwise great library, sad this is preventing me from using it :( !

**Comment by MeltingMosaic** [comment]
Hey, so I found a solution for a similar issue for #111 - could you maybe try the same thing? 
https://github.com/microsoft/tsyringe/issues/111#issuecomment-734003999

**Comment by nsyujian** [comment]
> Hey, so I found a solution for a similar issue for #111 - could you maybe try the same thing?
> [#111 (comment)](https://github.com/microsoft/tsyringe/issues/111#issuecomment-734003999)
> 
> If you don't have time, I can try this out soonish.

it works in react native

**Comment by Thomas-X** [comment]
Sorry for the late response, glad it works in react native with that solution! Maybe we could add a specific section for this fix to the documentation?

**Comment by jdiida** [comment]
I don't seem to get it to work in react-native, I'm getting this error: [SyntaxError: Invalid character: '@']
