### ISSUE TITLE
container.hasInstances() or some other way to tell if instances exist without creating new ones

### ISSUE THREAD

**Issue by mikl** [microsoft/tsyringe#127]
I’ve been struggling to find a way to gracefully shut down my Node.js application after adopting TSyringe, since there appears to be no way to get existing instances without creating a new one.

**Description**

For example, I have a database client defined as 

```typescript
@singleton()
export class CassandraClient {
  // Implementation irrelevant
}
```

and a shutdown function (using the global container) looking like this:

```typescript
  if (container.isRegistered(CassandraClient)) {
    for (const client of container.resolveAll(CassandraClient)) {
       client.shutdown())
    }
  }
```

…if no instances of the (singleton) CassandraClient exists, TSyringe instantiates a new one. Since I’m trying to shut down, that is counter-productive, and leads to problems trying to shut something down that hasn’t really started yet.

**Solutions**

I don’t really have a preference here, but I imagine one of these could solve the problem:

1. A `container.hasInstances()` check that only returns true if a token has been *instantiated*, not just registered.
2. A variant of (or parameter to) `container.resolveAll()` that only returns existing instances, instead of creating new ones.

**Comment by Xapphire13** [comment]
Could this be solved by checking to see if the client has been started before calling '.shutdown()'?

**Comment by mikl** [comment]
@Xapphire13 just instantiating the class starts it. I even tried subclassing the container to try to get at the existing instances without creating new ones, but since everything has `private` visibility, that’s not an option either :(

**Comment by Xapphire13** [comment]
@mikl, would you problem be solved by adding a `.dispose()` method to the container? This method would dispose all instances that implement:

```typescript
interface Disposable {
  dispose(): void;
}
```

and render the container unusable

**Comment by mikl** [comment]
@Xapphire13 yes, that would be a great solution, imho.
