### ISSUE TITLE
Singleton created multiple times

### ISSUE THREAD

**Issue by jekabs-karklins** [microsoft/tsyringe#158]
**Describe the bug**
Class decorated with @singleton is created multiple times.

**To Reproduce**
```typescript
// Foo.ts This is a singleton and must be created only once
import { singleton } from "tsyringe";

@singleton()
export class Foo {
  constructor() {
    console.log("Constructor of Foo");
  }
}
```

```typescript
// Bar.ts this is Bar and must be created every time. It uses the singleton
import { inject, injectable, Lifecycle, scoped } from "tsyringe";
import { Foo } from "./Foo";

@injectable()
export class Bar {
  constructor(@inject("Foo") private foo: Foo) {
    console.log("Constructor of Bar");
  }
}
```

```typescript
// main.ts this is resolving Bar two times.
import "reflect-metadata";
import { container } from "tsyringe";
import { Bar } from "./Bar";
import { Foo } from "./Foo";

container.register("Foo", { useClass: Foo });
container.register("Bar", { useClass: Bar });

const instance = container.resolve(Bar);
const instance1 = container.resolve(Bar);

```

**Expected behavior**
Console output
```bash
Constructor of Foo
Constructor of Bar
Constructor of Bar
```

**Actual behavior**
Console output
```bash
Constructor of Foo
Constructor of Bar
Constructor of Foo
Constructor of Bar
```

**Version**:
4.4.0

**Comment by MeltingMosaic** [comment]
You shouldn't use both `@singleton` and `@injectable` at the same time - I suspect that might be the cause of your issue.

**Comment by MeltingMosaic** [comment]
Ah, I think I have it - `@singleton` registers the type in the global container using the type as the injection token. Your call to `container.register("Foo", { useClass: Foo });` registers the type using the string `"Foo"` as the token. So a couple of possibilities here 
- remove the `Foo` registration, and remove the `@inject("Foo")` from the `Bar` ctor, or
- switch `Foo` to use `@injectable`, and register it using the singleton lifecycle like: `container.register("Foo", {useClass: Foo}, { lifecycle:Lifecycle.Singleton});`

**Comment by jekabs-karklins** [comment]
Thank you, that was it. Registering Foo like this solves the issue

```typescript
container.register(
  "Foo",
  { useClass: Foo },
  { lifecycle: Lifecycle.Singleton }
);
```
