### ISSUE TITLE
Providers are being resolved when not registered through any mechanism

### ISSUE THREAD

**Issue by rhyek** [microsoft/tsyringe#162]
**Describe the bug**
Providers are being resolved when not registered through any mechanism.

**To Reproduce**

```typescript
import 'reflect-metadata';
import { container } from 'tsyringe';

class UserService {
  get() {
    return { username: 'root' };
  }
}

const instance = container.resolve(UserService);

console.log('registered?', container.isRegistered(UserService));
console.log('instance found?', !!instance);
console.log('user:', instance?.get());
```

**Expected behavior**
should output:
```bash
registered? false
instance found? false
user: undefined
```

actual output:
```bash
registered? false
instance found? true
user: { username: 'root' }
```

**Version**: `4.5.0`

**Comment by rhyek** [comment]
Actually I was expecting some sort of error thrown which I think should be the correct behaviour.

**Comment by rhyek** [comment]
I understand now that `resolve` here is similar to inversify's `resolve`, but there is no `get` in tsyringe that provides a sort of "strict" alternative.

**Comment by mkq** [comment]
This is really dangerous for our use case. As described in #245, we use child containers for properly configured instances of OpenAPI-generated classes. If we accidentally resolve such a class from the root container, we will get an unwanted default instance which calls the base URL that the OpenAPI generator copied from the YAML spec into the code.

Guess I'll have to keep the GitHub workflow check that all servers in the YAMLs must be ….example.org. That check was meant to be removed once we have our DI / configuration set up.
