### ISSUE TITLE
Is there a way to auto bind `this` on all classes resolved by the container?

### ISSUE THREAD

**Issue by ylc395** [microsoft/tsyringe#186]
This is a common pattern in code base:

```js
const {method1, method2} = container.resolve(SomeService);
```
However, `method1`/`method2` has wrong `this` when calling them.

**Comment by BamboOSZ** [comment]
Have this same issue. Have to manually bind on every root resolve. Any chance for a fix/alternative solution to this?

**Comment by slier81** [comment]
the best way is to use arrow function instead since it has lexical scoping

**Comment by megastels** [comment]
doing this
```js
const {method1, method2} = container.resolve(SomeService);
```
is the same as 
```js
const {method1, method2} = new SomeService();
```
container shouldn't bind methods

if you really need bind methods, you can use something like this
https://www.npmjs.com/package/autobind-decorator
or use arrow functions
