### ISSUE TITLE
When will DependencyContainer.dispose be published to npm?

### ISSUE THREAD

**Issue by XC-Zhang** [microsoft/tsyringe#194]
[Disposing container](https://github.com/microsoft/tsyringe/commit/675c3c458d64aa6ce56b87aa74c95b0627539bb7) has been added to master but not yet published to npm. Is there any plan?

**Comment by Socolin** [comment]
Hello,

I'm also interested by this, could a new version be published ?

**Comment by MeltingMosaic** [comment]
I just published it. Apologies for the delay,
