### ISSUE TITLE
Abstract class constructor type issue

### ISSUE THREAD

**Issue by unlocomqx** [Microsoft/tsyringe#20]
I tried using the injectable decorator with an abstract class but it gave me this error

```
Argument of type 'typeof MyClass' is not assignable to parameter of type 'constructor<{}>'.
      Cannot assign an abstract constructor type to a non-abstract constructor type.
```

Sample code
```
import { injectable } from "tsyringe";

@injectable()
abstract class MyClass {

}
```

I modified the declaration just to test (based on https://stackoverflow.com/questions/36886082/abstract-constructor-type-in-typescript)
```
type abstract_ctor<T> = Function & { prototype: T };
export declare function injectable<T>(): (target: constructor<T>|abstract_ctor<T>) => void;
```
and the compilation worked without errors

I will try cloning and running some tests to see if DI works fine with an abstract class

**Comment by Xapphire13** [comment]
I believe this is by design. Abstract classes cannot be instantiated, and therefore cannot (should not?) be injected.

What is your use case? Does the following solve it?

```typescript
abstract class MyBase {
}

@injectable()
class MyClass extends MyBase {
}
```

**Comment by unlocomqx** [comment]
Thank you for the hint, I didn't think it would work like that (coming from inversify)
Your example works, but the following doesn't

```
test("abstract class autoinjectable", () => {
  class Foo {}
  abstract class MyBase {
    constructor(public foo: Foo){}
  }

  @injectable()
  class MyClass extends MyBase {
  }

  const instance: MyBase = globalContainer.resolve(MyClass);
  expect(instance.foo instanceof Foo).toBeTruthy();
});
```

Do you think it can be implemented? Is the concept correct at least?

If not I can just duplicate the constructor in my child classes

Thank you

**Comment by Xapphire13** [comment]
Ahh, got it. This is an interesting problem; we dont want the abstract base to be registered, but we also dont want to duplicate the constructor in the derived type.

Let me take a look at what info we have access to in the decorator method at runtime. The way its working right now is the decorator is given the constructor of the decorated class, then we iterate over the parameters and store them in a dictionary for future lookup. Looks like we need to also check any base classes and do the same (if possible).

**Comment by unlocomqx** [comment]
I tried registering the abstract class using `@autoInjectable` in my PR #21 which worked fine except for a type error on 
`return class extends target ` because I changed the `constructor` type.
Error message: `Type constructor<any> is not a constructor function type`
https://travis-ci.org/Microsoft/tsyringe/jobs/477314771

I didn't find another way since the base constructor must be altered

But anyway, the base class seems to be present in the metadata 
So we may take the base constructor params, instantiate them and assign them as props of the derived class, I don't know if it can be done or if it's a clean solution
![2019-01-10_13-46](https://user-images.githubusercontent.com/793712/50969262-340be200-14de-11e9-8bf1-bb1b342c4257.png)

**Comment by Xapphire13** [comment]
Nice, if you have some time, can you see if `getParamInfo(target.prototype.constructor)` returns the correct param infos?

**Comment by unlocomqx** [comment]
I tried this code but no luck
```
export function injectable<T>(): (target: constructor<T>) => void {
  return function(target: constructor<T>): void {
    typeInfo.set(target, getParamInfo(target));
    const base = Object.getPrototypeOf(target);
    if (base.name) {
      const params = getParamInfo(base);
      const params2 = getParamInfo(base.constructor);
      console.log(params);
      console.log(params2);
      typeInfo.set(target, getParamInfo(base));
    }
  };
}
```

`target.prototype.constructor` gave me the derived class, that's why I tried using `Object.getPrototypeOf(target)`
But it seems that in runtime, the param type info isn't available

I'll give it another try, if you have any suggestions, please let me know

**Comment by unlocomqx** [comment]
I got it to return the correct param infos by adding a dummy decorator just to test

```
export type abstract_constructor<T> = Function & { prototype: T};
// ...
export function dummyDecorator(): (target: abstract_constructor<any>) => any {
  return function(target: abstract_constructor<any>): abstract_constructor<any> {
    return target;
  };
}
```

`reflect-metadata` wouldn't work without the decorator

I still have to assign the instance property `foo` somehow though (referring to code in https://github.com/Microsoft/tsyringe/issues/20#issuecomment-452899083)

**Comment by unlocomqx** [comment]
This makes my PR solution the simplest (except for the type issue described in https://github.com/Microsoft/tsyringe/issues/20#issuecomment-453085278)

**Comment by unlocomqx** [comment]
I'll close this issue as it's just a type issue after all with no runtime issues.
I was able to get me going using a @ts-ignore before the `autoInjectable`
The other issue I faced was circular dependency which I solved using a `lazyInject` property decorator
https://github.com/unlocomqx/tsyringe/commit/a135eacc6fa3820c0124f285777c2767153f970a
If this is something that's interesting to have in the lib, please tell me so I can make a PR

Cheers
