### ISSUE TITLE
Option for Disabling Lazy Loading

### ISSUE THREAD

**Issue by Sn0bli** [microsoft/tsyringe#22]
Is there an option to disable lazy initialization on instances?
It could be useful if the objects are initialized at start, not on first usage.

I may have missed something but i can not see this option.

Thanks a lot!

**Comment by Xapphire13** [comment]
I assume you are talking about the `@singleton` decorator? As other dependencies are resolved transiently (as needed)?

**Comment by Sn0bli** [comment]
Yeah exactly, I forgot to mention that.
Not sure if it's even possible in JS..

**Comment by Xapphire13** [comment]
Could you give a little more info on your use case?

**Comment by Sn0bli** [comment]
In this case, initialization takes a few seconds async waiting for external parts. 
ATM i'm calling the instance at the startup of the application, which works as a workaround.

**Comment by Xapphire13** [comment]
So something such as `@singleton({lazy: false})`?

@MeltingMosaic, what do you think?

**Comment by MeltingMosaic** [comment]
I think that `container.registerInstance(...)` is the clearest way to accomplish what you want. Using a decorator to do this seems fishy.
