### ISSUE TITLE
In case it's useful to anybody else, I have a fork of this repo with this fix included (and compiled files checked in, so it can be used as an npm dependency): https://github.com/tec27/tsyringe

### ISSUE THREAD

**Issue by joaohenriquesouza80** [microsoft/tsyringe#228]
In case it's useful to anybody else, I have a fork of this repo with this fix included (and compiled files checked in, so it can be used as an npm dependency): https://github.com/tec27/tsyringe

You can use it by changing your package.json dep to:
```json
"tsyringe": "tec27/tsyringe#43d00160db294312db4c7deb38046f71dcd74348"
```

_Originally posted by @tec27 in https://github.com/microsoft/tsyringe/issues/226#issuecomment-1593830738_

So many thanks :)

**Comment by MeltingMosaic** [comment]
I have updated the official package to 4.8.0. Thanks for doing this in the interim though!
