### ISSUE TITLE
Plans for request scope (non-transient)?

### ISSUE THREAD

**Issue by allardmuis** [microsoft/tsyringe#25]
Hello Tsyringe team,

I was wondering if there are any plans for supporting a 'request' scope. I'll give an example of what I mean:

```
@injectable()
class A {
  constructor(public b: B, public c: C) {}
}
class B {
  constructor(public x: X) {}
}
class C {
  constructor(public x: X) {}
}
@requestScope()
class X {}

const a = container.resolve(A);
a.b.x === a.c.x; // within a single dependency resolution inject the same instance instead of creating new ones. 
```

This can sometimes be very useful, for example if X sets up a database transaction that has to be used by anything _within_ the container.resolve call, but not for subsequent calls to container.resolve.

Thanks!

**Comment by MeltingMosaic** [comment]
This is an interesting idea. I haven't thought about it too deeply, but I think there might be a way using Factories, but I haven't thought of a non-janky way to implement this. Right now, we don't have the concepts of "resolution start" and "resolution end", which might be necessary to make this work cleanly.

**Comment by allardmuis** [comment]
Thanks for the response. I'll close the issue as I understand this cannot be implemented for now.

**Comment by Xapphire13** [comment]
Re-opening the issue since I feel there could be some work to be done here.
