### ISSUE TITLE
Testing singletons

### ISSUE THREAD

**Issue by heathbar** [microsoft/tsyringe#28]
I'm writing tests against a class marked `@singleton()`. In my `beforeEach` I resolve the class, but since it's a singleton I get the same instance for each test. Ideally each test would be independent of the others. I tried calling `container.reset()` but that wipes out all of the registered types. Is there room in this library for a "soft" reset, or is there another approach I could take?

**Comment by Xapphire13** [comment]
Are you thinking something like:

```typescript
container.clear(myToken);
```

**Comment by Xapphire13** [comment]
Also, could you give a snippet of your `beforeEach(...)`? I'm wondering if directly resolving your singleton class could solve the issue (via `new ...`)

**Comment by fabiopigna** [comment]
What we would have is a way to clean only the already created instances and keep the register token. In this way we clear the "status" of the `DependecyContainer`  but we still able to create new singleton instances by `container.resolve(...)`

for example:

```
export class DependencyContainer implements Types.DependencyContainer {

/**
   * Clears all instances of registered tokens
   */
  public clearInstances(): void {
    this._registry.forEach((value) => {
      value.instance = undefined;
    });
  }
```

Could it be a valid solution?

**Comment by heathbar** [comment]
My intention is to start from a clean/pristine state before each tests so that one test does not interfere with another. The solution by @fabiopigna does help in the case of testing variations of a singleton dependency, but there are other cases where this solution is not sufficient. For example, the following code sets up a class and it's dependency. We then successfully test that class with a mock dependency, but when we get to testing the service we run into issues. 

```TypeScript
@singleton
class MyClass {
    constructor(private service: MyService) { }
    callService() {
        this.service.doTask();
    }
}
@singleton
class MyService {
    doTask() {
        // real implementation
    }
}
@singleton
class MyServiceMock {
    doTask() {
        // mock implementation
    }
}

/// Jasmine tests for MyClass ///

describe('MyClass suite', () => {
    let myClass: MyClass;
    let myService: MyService;

    beforeEach(() => {
        // Mock out the real implementation with a mock
        container.registerInstance(MyService, MyServiceMock);
        
        // Retrieve an instance of MyClass with a mock dependency
        myClass = container.resolve(MyClass);

        // Since MyService is a singleton, we can get a hold of the same instance that was given to MyClass
        myService = container.resolve(MyService);
    });

    it('should have a mock service', () => {
        spyOn(myService, 'doTask');
        myClass.callService();
        expect(myService.doTask).toHaveBeenCalled();
    });
});

/// Jasmine tests for MyService ///

describe('MyService suite', () => {
    let myService: MyService; 

    beforeEach(() => {

        // Since the container never resets, this returns MyServiceMock, but I want to test the real MyService
        myService = container.resolve(MyService);
    })
});
```
I recognize that there are a few solutions. 
1. Call container.reset() in my beforeEach. The problem is that then I would need to manually re-register all classes manually which defeats the benefit of having decorators. 
1. Re-register the real service in the beforeEach: `container.registerInstance(MyService, MyService)`, but this feels more like addressing the symptom and not the cause since the container still evolves (maintains state) throughout the lifecycle of the test suite.
1. Instantiate `MyService` using the `new` operator in the `MyService` test suite. This defeats the purpose of the library. Additionally, if `MyService` has a large chain of dependencies, this becomes cumbersome.

Currently, I've managed to 'snapshot' the container after all decorators have registered, but before any tests run with the help of `lodash.clonedeep`. Then I restore the snapshot before each test globally.

```TypeScript
let pristineRegistry: Map<any, any>;

beforeAll(() => {
    pristineRegistry = cloneDeep((container as any)._registry);
});

beforeEach(() => {
    (container as any)._registry = cloneDeep(pristineRegistry);
});
```
It's an ugly hack, but it accomplishes my goal of having a clean container with all of my decorated classes pre-loaded before each test.

**Comment by MeltingMosaic** [comment]
I wonder if child containers are the way to solve this issue - I haven't tried this, but I wonder if

```
/// Jasmine tests for MyClass ///

describe('MyClass suite', () => {
    let myClass: MyClass;
    let myService: MyService;
    let childContainer = container.createChildContainer();
    beforeEach(() => {
        // Mock out the real implementation with a mock
        childContainer.registerInstance(MyService, MyServiceMock);
        
        // Retrieve an instance of MyClass with a mock dependency
        myClass = childContainer.resolve(MyClass);

        // Since MyService is a singleton, we can get a hold of the same instance that was given to MyClass
        myService = childContainer.resolve(MyService);
    });

    it('should have a mock service', () => {
        spyOn(myService, 'doTask');
        myClass.callService();
        expect(myService.doTask).toHaveBeenCalled();
    });
});

/// Jasmine tests for MyService ///

describe('MyService suite', () => {
    let myService: MyService; 

    beforeEach(() => {

        // Since the container never resets, this returns MyServiceMock, but I want to test the real MyService
        myService = container.resolve(MyService);
    })
});
```

**Comment by skiptirengu** [comment]
Just a heads up. You can do this cleanly with the new ContainerScoped lifecycle introduced on version 4. ContainerScoped behaves pretty much like a singleton, except the cached instance is reset for every new child container created.


```ts
import { Lifecycle, scoped, container as globalContainer } from 'tsyringe'

@scoped(Lifecycle.ContainerScoped)
class MyService {
  // ...
}

describe('My test', () => {
  let container: DependencyContainer

  beforeEach(function () => {
    container = globalContainer.createChildContainer()
  })

  it('New MyService instance', () => {
    const instance = container.resolve(MyService)
    // ...
  })
})
```

**Comment by maurits-tellow** [comment]
@skiptirengu Thank you for the tip!

To me this still feels like a workaround though, because the class definitions have to be changed for testing purposes. I would prefer using `@singleton()` and have a method for clearing instances during testing. `container.clear()` or `.clearInstances()` for example.

This is the current situation:

```typescript
import assert from 'assert'
import 'reflect-metadata'
import { singleton, container } from 'tsyringe'

@singleton()
class Foo {
  constructor() {
    console.log('Foo constructor')
  }
}

let instance, instance2

instance = container.resolve(Foo) // -> Logs "Foo constructor"
instance2 = container.resolve(Foo)
assert.strictEqual(instance, instance2)

container.reset()
// Foo is now no longer registered as singleton

instance = container.resolve(Foo) // -> Logs "Foo constructor"
instance2 = container.resolve(Foo) // -> Logs "Foo constructor"
assert.notStrictEqual(instance, instance2)
```

This is my hacky `clearContainerInstances` helper function that I'm currently using for testing:

```typescript
import assert from 'assert'
import 'reflect-metadata'
import { singleton, container } from 'tsyringe'

@singleton()
class Foo {
  constructor() {
    console.log('Foo constructor')
  }
}

import { isValueProvider } from 'tsyringe'

function clearContainerInstances(container) {
  const registry = (container as any)._registry

  for (const [token, registrations] of registry.entries()) {
    registry.setAll(
      token,
      registrations
        // Clear registrations from container.registerInstance() calls
        .filter(registration => !isValueProvider(registration.provider))
        // Clear instances
        .map(registration => {
          registration.instance = undefined
          return registration
        }),
    )
  }
}

let instance, instance2

instance = container.resolve(Foo) // -> Logs "Foo constructor"
instance2 = container.resolve(Foo)
assert.strictEqual(instance, instance2)

clearContainerInstances(container)

instance = container.resolve(Foo) // -> Logs "Foo constructor"
instance2 = container.resolve(Foo)
assert.strictEqual(instance, instance2)

container.registerInstance(Foo, instance2)
clearContainerInstances(container)

instance = container.resolve(Foo) // -> Logs "Foo constructor"
instance2 = container.resolve(Foo)
assert.strictEqual(instance, instance2)
```

I think an explanation about `container.reset()` in the README would clear up confusion. I initially assumed it cleared instances and **not** the registrations made by decorators like `@singleton()`.

**Comment by Xapphire13** [comment]
Thanks for the clear description, I'm going to close this issue in favor of the following two issues I created too track the discussion above:

- #82 
- #83
