### ISSUE TITLE
Injecting third party Class (Singleton scope)

### ISSUE THREAD

**Issue by laurensdijkstra** [microsoft/tsyringe#36]
Hi,

I have been experimenting with this library and I'm trying to resolve an instance of ApolloClient which I registered as an instance via `registerInstance`. The instance uses a configuration that I manually inject via `container.resolve`, like so: 
```
container.registerInstance(
    "ApolloClient",
    new ApolloClient(container.resolve(ApolloClientConfiguration))
);
```
`ApolloClientConfiguration` is my own class which has an `@injectable` decorator. The issue I'm having is that Tsyringe throws `Error: TypeInfo not known for function ApolloClient(options) { ...`. Is it possible to register and inject third party Classes with Tsyringe?

I resolve the instance with
```
const apolloClient = container.resolve<ApolloClient<NormalizedCacheObject>>(
    "ApolloClient"
);
```

Thanks

**Comment by MeltingMosaic** [comment]
Can you post the code where you are resolving the instance?

**Comment by laurensdijkstra** [comment]
```const apolloClient = container.resolve<ApolloClient<NormalizedCacheObject>>(
    "ApolloClient"
);```

**Comment by laurensdijkstra** [comment]
That information was indeed missing, I have added it to the original post.

**Comment by MeltingMosaic** [comment]
I think I see the problem, though I haven't tested it to be certain. I think when you register the instance, you need to register with the type, since when you resolve the type, we check to see if the type you're resolving is the type that was registered. Does it work if you register the instance as `ApolloClient<NormalizedCacheObject>`?

**Comment by laurensdijkstra** [comment]
It works when I use `@inject(ApolloClient)`. Thanks
