### ISSUE TITLE
How to handle several container scenarios?

### ISSUE THREAD

**Issue by fab971** [microsoft/tsyringe#43]
**Is your feature request related to a problem? Please describe.**
I have a use case where I need to be able to manage multiple containers each with specific settings. By settings I mean a different object to inject to the last nested object.

**Description**
To do so It would be very great if we could instantiate containers this way:

```
let container1 = new Container();
let container2 = new Container();
```

And then "attach" the settings object (in my use case) to containers like this:

```
container1.register("SettingsClass", {
  provider: () => settingsObject1
});
container2.register("SettingsClass", {
  provider: () => settingsObject2
});
```

So when resolving objects the right settingsObject1 will be injected and successfully get 

```
const myService1 = container1.resolve(MyService);
const myService2 = container2.resolve(MyService);
```

Maybe there is already a way to do it but I could not find it, could you help me?
PS: I'm a noob in typescript :)

**Comment by skiptirengu** [comment]
You can create a new container instance with `container.createChildContainer()`, since the `DepedencyContainer` class is not exported.

Every container instance has it's own `Registry` but also holds a reference to it's parent and will use it to resolve depedencies only when a given depedency is not found within it's own registry.

Changing your example to the following will probably solve your problem.

```ts
import {container} from 'tsyringe';

const container1 = container;
const container2 = container.createChildContainer();

container1.register("SettingsClass", {
  provider: () => settingsObject1
});
container2.register("SettingsClass", {
  provider: () => settingsObject2
});

console.log(container1.resolve("SettingsClass") === container2.resolve("SettingsClass"));
````

**Comment by Xapphire13** [comment]
You could also create two child containers and not use the root container at all. That way you won't have the child container fallback on what you register in the other container.

**Comment by fab971** [comment]
Ok thank you, it's perfect 👌

**Comment by Xapphire13** [comment]
Going to leave this open until the documentation for this is in the readme

**Comment by MeltingMosaic** [comment]
@Xapphire13 I'm in the process of updating the documentation - what exactly needs to be documented here? That you can have multiple containers, or that you can have containers with fallback using `createChildContainer()`?
