### ISSUE TITLE
Vanilla Javascript examples

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/tsyringe#44]
> A lightweight dependency injection container for TypeScript/JavaScript for constructor injection.

But I only see typescript examples and no javascript only example. Is it even possible to use it without typescript?

**Comment by Xapphire13** [comment]
It's possible in JavaScript, but most likely not vanilla JavaScript.

Since decorators aren't part of the official JavaScript spec yet you would need to use something like https://babeljs.io/docs/en/babel-plugin-proposal-decorators.

**Comment by bm-stschneider** [comment]
what about the decorator pattern? you don't necessarily need the decorator notation.

**Comment by Xapphire13** [comment]
To expand on my previous answer, this _is_ possible in vanilla JS, but likely not worth the effort. Both TypeScript and the babel plugin will generate vanilla JS (which is the proof it's possible in vanilla JS). Manually writing the code to simulate the decorator syntax would add a lot of boilerplate to your project.

I'd love to see an example of what it would look like, but I feel that's beyond the scope of this project.
