### ISSUE TITLE
npm package v3.3.0 missing resolveAll method in DependencyContainer interface

### ISSUE THREAD

**Issue by codymartin** [microsoft/tsyringe#52]
**Describe the bug**
The documentation suggests v3.3.0 has resolveAll implemented but its not in the published package. 

**To Reproduce**
1. npm install tsyringe, notice package.json is v3.3.0
2. notice dist\typings\types\dependency-container.d.ts is missing resolveAll method
3. notice also missing from all dependency-container.js files

**Expected behavior**
it should be there

**Version**:
3.3.0

**Comment by MeltingMosaic** [comment]
Releaste 3.4.0 which should have this.
