### ISSUE TITLE
Not working with default values

### ISSUE THREAD

**Issue by holwech** [microsoft/tsyringe#74]
Please correct me if I'm wrong, but it doesn't seem like tsyringe is working with default constructor values? It would be nice if the default values would be used if no value for the input is provided. Example:

```typescript
import 'reflect-metadata';
import { container } from 'tsyringe';

class TestClass {
  constructor(private str: string = 'string') {}
}

let instance = container.resolve<TestClass>(TestClass);
```
Gives the following error:
```
    TypeInfo not known for function TestClass(str) {

              if (str === void 0) { str = 'string'; }
              this.str = str;
          }
```

Preferably this would run and the `str` variable would be set to the default value of `"string"`.

**Comment by skiptirengu** [comment]
The following test case works for me:

```ts
class TestClass {
  constructor(private str: string = "string") {}

  public print(): void {
    console.log(this.str);
  }
}

const instance = globalContainer.resolve<TestClass>(TestClass);
expect(instance).toBeInstanceOf(TestClass);
instance.print();
```

Are you using some kind of JavaScript transpiler like Babel?

**Comment by holwech** [comment]
Thanks for your response. So the tsc compiler was set to target ES5 which does not support default parameters natively and that's probably what caused the error. Setting the target to ES6 solved the issue and everything seems to be working fine now :)
