### ISSUE TITLE
export DependencyContainer type

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/tsyringe#75]
I have this in several files where I configure via factory methods, 

    import DependencyContainer from 'tsyringe/dist/typings/types/dependency-container';

would be nice if I could just do `import DependencyContainer from 'tsyringe'` example
```ts
@registry([
  { token: InjectToken.ApolloProvider, useClass: ApolloProvider },
  { token: InjectToken.ContentfulProvider, useClass: ContentfulProvider },
  { token: InjectToken.StripeProvider, useClass: StripeProvider },
])
export default class BootStrapper {

  constructor(private readonly container: DependencyContainer) {
  }

  async registerAll(): Promise<void> {
    await new RegistryConfigurer(this.container).registerAll();
  }

  async getApolloServer(): Promise<ApolloServer> {
    await this.registerAll();
    return this.container.resolve<ApolloServer>(InjectToken.ApolloServer);
  }
}
```

**Comment by xenoterracide** [comment]
nevermind, this is something dumb that intellij is doing apparently

**Comment by Xapphire13** [comment]
Looks like intellij is trying to tree shake by default?

**Comment by xenoterracide** [comment]
I'm not sure, only does this with `DependencyContainer`

**Comment by Xapphire13** [comment]
🤷‍♂, probably just something to do with how IntelliJ caches/discovers modules
