### ISSUE TITLE
factories resolution scope

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/tsyringe#77]
>  - ResolutionScoped
>   - The same instance will be resolved for each resolution of this dependency during a single
>   resolution chain

are factories resolution scoped? or will more than one thing be resolved if the factory is not cached?

doc bug, will fix with clarity

**Comment by Xapphire13** [comment]
This block of code prohibits scopes from being used with Factories: https://github.com/microsoft/tsyringe/blob/4a104cccb1e8ffed142e38441788bf524b7151d3/src/dependency-container.ts#L76-L86

Which means that the factory will be used for the container it's registered with and all of that containers children.
