### ISSUE TITLE
"file" scanning

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/tsyringe#94]
I think it's possible to implement a file scanner compiler plugin, on that looks for things like @registry, @singleton, etc, that would automatically include them so that they don't need to be explicitly imported anywhere, this would be especially useful for ticket #68, and other things that allow decentralization like building a server side framework for large apps using decorators like @controller, I found this

https://github.com/basarat/typescript-book/blob/master/docs/compiler/scanner.md

**Comment by Xapphire13** [comment]
Could you elaborate on the use case a little more? Newer versions of TSServer offer auto import intellisense actions (if that's the kinda of thing you're trying to achieve?)

**Comment by xenoterracide** [comment]
it's not an auto import thing... it's a no import thing, but I doubt this is a tsyringe thing.

**Comment by Xapphire13** [comment]
Ohh, I think I see what you were suggesting. And yeah, I think that would be external to this project.
